name: random_starter
description: "A randomizer for starter speaker in immo daily in Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  flutter_fortune_wheel: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true